# Navigation Links
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    url: /
    weight: 10
  - name: Working Papers
    url: working_papers/
    weight: 20
  - name: My Photos
    url: /
    weight: 30
